const Car = require('../models/Car');
const Driver = require('../models/Driver');

// 35 realistic Bangladeshi car demo records with corresponding images
const carData = [
  {
    name: 'টয়োটা এক্সিও এক্স হাইব্রিড ২০১৮',
    brand: 'Toyota',
    model: 'Axio',
    registrationNumber: 'DHA-GA-11-2001',
    carType: 'sedan',
    year: 2018,
    seatingCapacity: 5,
    fuelType: 'hybrid',
    transmission: 'automatic',
    dailyRentalPrice: 3500,
    images: ['/uploads/cars/toyota-axio-01.jpg'],
    description: 'দৈনন্দিন সিটি রাইড ও পারিবারিক সফরের জন্য পারফেক্ট ও জ্বালানি সাশ্রয়ী প্রিমিয়াম সেডান গাড়ি। সম্পূর্ণ এসি ও আরামদায়ক সিট।',
    status: 'available',
    assignedDriver: null,
    currentMileage: 48500,
  },
  {
    name: 'টয়োটা করোলা আলটিস ২০১৯',
    brand: 'Toyota',
    model: 'Corolla Altis',
    registrationNumber: 'DHA-GA-11-2002',
    carType: 'sedan',
    year: 2019,
    seatingCapacity: 5,
    fuelType: 'octane',
    transmission: 'automatic',
    dailyRentalPrice: 3800,
    images: ['/uploads/cars/toyota-corolla-altis-01.jpg'],
    description: 'স্মুথ ড্রাইভিং এক্সপেরিয়েন্স ও আকর্ষণীয় লুকের এক্সিকিউটিভ সেডান। হাইওয়ে ও সিটিতে সেরা পারফরম্যান্স।',
    status: 'available',
    assignedDriver: null,
    currentMileage: 42000,
  },
  {
    name: 'টয়োটা প্রিমিও এফ ২০১৭',
    brand: 'Toyota',
    model: 'Premio',
    registrationNumber: 'DHA-GA-11-2003',
    carType: 'sedan',
    year: 2017,
    seatingCapacity: 5,
    fuelType: 'octane',
    transmission: 'automatic',
    dailyRentalPrice: 4200,
    images: ['/uploads/cars/toyota-premio-01.jpg'],
    description: 'ভিআইপি ও কর্পোরেট ট্রিপের জন্য অত্যন্ত আরামদায়ক লাক্সারি সেডান। উন্নত পুশ-স্টার্ট ও ক্লাইমেট কন্ট্রোল এসি।',
    status: 'available',
    assignedDriver: null,
    currentMileage: 56000,
  },
  {
    name: 'টয়োটা অ্যালিয়ন এ১৫ ২০১৮',
    brand: 'Toyota',
    model: 'Allion',
    registrationNumber: 'DHA-GA-11-2004',
    carType: 'sedan',
    year: 2018,
    seatingCapacity: 5,
    fuelType: 'octane',
    transmission: 'automatic',
    dailyRentalPrice: 4000,
    images: ['/uploads/cars/toyota-allion-01.jpg'],
    description: 'স্টাইলিশ লুক এবং আরামদায়ক ইন্টেরিয়র সমন্বিত সেরা সেডান কার। পরিবারের সাথে দূরপাল্লার ভ্রমণে নির্ভরযোগ্য।',
    status: 'available',
    assignedDriver: null,
    currentMileage: 51200,
  },
  {
    name: 'টয়োটা নোয়াহ এক্স ২০১৭',
    brand: 'Toyota',
    model: 'Noah',
    registrationNumber: 'DHA-CHA-51-2005',
    carType: 'microbus',
    year: 2017,
    seatingCapacity: 7,
    fuelType: 'octane',
    transmission: 'automatic',
    dailyRentalPrice: 5500,
    images: ['/uploads/cars/toyota-noah-01.jpg'],
    description: '৭ জনের পারিবারিক ও গ্রুপ ট্যুরের জন্য স্পেশাস ও রিল্যাক্সিং মিনিভ্যান। ডুয়েল এসি এবং পর্যাপ্ত লাগেজ স্পেস।',
    status: 'available',
    assignedDriver: null,
    currentMileage: 64000,
  },
  {
    name: 'টয়োটা হায়েস সুপার জিএল ২০১৬',
    brand: 'Toyota',
    model: 'Hiace Super GL',
    registrationNumber: 'DHA-CHA-51-2006',
    carType: 'microbus',
    year: 2016,
    seatingCapacity: 11,
    fuelType: 'diesel',
    transmission: 'manual',
    dailyRentalPrice: 6500,
    images: ['/uploads/cars/toyota-hiace-01.jpg'],
    description: 'বড় দল বা অফিসের অফিসিয়াল পিকনিক ও ট্যুরের জন্য ১১ সিটের পাওয়ারফুল ও টেকসই মাইক্রোবাস।',
    status: 'available',
    assignedDriver: null,
    currentMileage: 89000,
  },
  {
    name: 'টয়োটা ভক্সি হাইব্রিড ২০১৯',
    brand: 'Toyota',
    model: 'Voxy',
    registrationNumber: 'DHA-CHA-51-2007',
    carType: 'microbus',
    year: 2019,
    seatingCapacity: 7,
    fuelType: 'hybrid',
    transmission: 'automatic',
    dailyRentalPrice: 5800,
    images: ['/uploads/cars/toyota-voxy-01.jpg'],
    description: 'মডার্ন অ্যারোডাইনামিক ডিজাইন ও হাইব্রিড ফুয়েল এফিশিয়েন্ট ৭ সিটার লাক্সারি ফ্যামিলি ভ্যান।',
    status: 'available',
    assignedDriver: null,
    currentMileage: 39000,
  },
  {
    name: 'টয়োটা ইয়ারিস ক্রস ২০২১',
    brand: 'Toyota',
    model: 'Yaris Cross',
    registrationNumber: 'DHA-GHA-13-2008',
    carType: 'suv',
    year: 2021,
    seatingCapacity: 5,
    fuelType: 'hybrid',
    transmission: 'automatic',
    dailyRentalPrice: 5000,
    images: ['/uploads/cars/toyota-yaris-cross-01.jpg'],
    description: 'কমপ্যাক্ট আধুনিক এসইউভি। উচ্চ গ্রাউন্ড ক্লিয়ারেন্স ও হাই-টেক সেফটি ফিচারযুক্ত কমফোর্টেবল কার।',
    status: 'available',
    assignedDriver: null,
    currentMileage: 28000,
  },
  {
    name: 'টয়োটা হিলাক্স রেভো ২০২০',
    brand: 'Toyota',
    model: 'Hilux Revo',
    registrationNumber: 'DHA-THA-11-2009',
    carType: 'pickup',
    year: 2020,
    seatingCapacity: 5,
    fuelType: 'diesel',
    transmission: 'manual',
    dailyRentalPrice: 7500,
    images: ['/uploads/cars/toyota-hilux-01.jpg'],
    description: 'অফ-রোড অ্যাডভেঞ্চার ও মালামাল পরিবহনে শক্তিশালী ফোর-হুইল ড্রাইভ ডাবল কেবিন পিকআপ।',
    status: 'available',
    assignedDriver: null,
    currentMileage: 45000,
  },
  {
    name: 'টয়োটা ল্যান্ড ক্রুজার প্রাডো ২০১৮',
    brand: 'Toyota',
    model: 'Land Cruiser Prado',
    registrationNumber: 'DHA-GHA-13-2010',
    carType: 'suv',
    year: 2018,
    seatingCapacity: 7,
    fuelType: 'diesel',
    transmission: 'automatic',
    dailyRentalPrice: 12000,
    images: ['/uploads/cars/toyota-prado-01.jpg'],
    description: 'ভিআইপি প্রটোকল, লং হাইওয়ে ট্যুর ও আভিজাত্যের প্রতীক ৭ সিটার ফুল-সাইজ লাক্সারি এসইউভি।',
    status: 'available',
    assignedDriver: null,
    currentMileage: 62000,
  },
  {
    name: 'হোন্ডা সিভিক টার্বো ২০২০',
    brand: 'Honda',
    model: 'Civic',
    registrationNumber: 'DHA-GA-11-2011',
    carType: 'sedan',
    year: 2020,
    seatingCapacity: 5,
    fuelType: 'octane',
    transmission: 'automatic',
    dailyRentalPrice: 4800,
    images: ['/uploads/cars/honda-civic-01.jpg'],
    description: 'স্পোর্টি লুক, টার্বোচার্জড পাওয়ার ও প্রিমিয়াম সাউন্ড সিস্টেমযুক্ত স্টাইলিশ এক্সিকিউটিভ সেডান।',
    status: 'available',
    assignedDriver: null,
    currentMileage: 34000,
  },
  {
    name: 'হোন্ডা গ্রেস হাইব্রিড ২০১৮',
    brand: 'Honda',
    model: 'Grace',
    registrationNumber: 'DHA-GA-11-2012',
    carType: 'sedan',
    year: 2018,
    seatingCapacity: 5,
    fuelType: 'hybrid',
    transmission: 'automatic',
    dailyRentalPrice: 3600,
    images: ['/uploads/cars/honda-grace-01.jpg'],
    description: 'চমৎকার মাইলেজ ও আরামদায়ক সিটিং পজিশনযুক্ত অত্যন্ত জনপ্রিয় হাইব্রিড সেডান।',
    status: 'available',
    assignedDriver: null,
    currentMileage: 49000,
  },
  {
    name: 'হোন্ডা ভেজেল জেড হাইব্রিড ২০১৯',
    brand: 'Honda',
    model: 'Vezel',
    registrationNumber: 'DHA-GHA-13-2013',
    carType: 'suv',
    year: 2019,
    seatingCapacity: 5,
    fuelType: 'hybrid',
    transmission: 'automatic',
    dailyRentalPrice: 4600,
    images: ['/uploads/cars/honda-vezel-01.jpg'],
    description: 'আরবান ক্রুজিং ও হাইওয়ে ভ্রমণের সেরা কম্বিনেশন। আধুনিক ফিচার ও প্রিমিয়াম ইন্টেরিয়র।',
    status: 'available',
    assignedDriver: null,
    currentMileage: 41000,
  },
  {
    name: 'হোন্ডা সিআর-ভি ২০১৮',
    brand: 'Honda',
    model: 'CR-V',
    registrationNumber: 'DHA-GHA-13-2014',
    carType: 'suv',
    year: 2018,
    seatingCapacity: 5,
    fuelType: 'octane',
    transmission: 'automatic',
    dailyRentalPrice: 6200,
    images: ['/uploads/cars/honda-cr-v-01.jpg'],
    description: 'প্রশস্ত কেবিন, সানরুফ ও শক্তিশালী ইঞ্জিন সমন্বিত প্রিমিয়াম মিড-সাইজ এসইউভি কার।',
    status: 'available',
    assignedDriver: null,
    currentMileage: 53000,
  },
  {
    name: 'হোন্ডা ফিট হাইব্রিড ২০১৯',
    brand: 'Honda',
    model: 'Fit',
    registrationNumber: 'DHA-KHA-11-2015',
    carType: 'hatchback',
    year: 2019,
    seatingCapacity: 5,
    fuelType: 'hybrid',
    transmission: 'automatic',
    dailyRentalPrice: 3000,
    images: ['/uploads/cars/honda-fit-01.jpg'],
    description: 'ঢাকার শহরের ট্রাফিকের জন্য সহজে পার্কিংযোগ্য ও দ্রুত মুভমেন্টের জন্য আদর্শ হ্যাচব্যাক।',
    status: 'available',
    assignedDriver: null,
    currentMileage: 36000,
  },
  {
    name: 'নিসান এক্স-ট্রেইল হাইব্রিড ২০১৮',
    brand: 'Nissan',
    model: 'X-Trail',
    registrationNumber: 'DHA-GHA-13-2016',
    carType: 'suv',
    year: 2018,
    seatingCapacity: 5,
    fuelType: 'hybrid',
    transmission: 'automatic',
    dailyRentalPrice: 5200,
    images: ['/uploads/cars/nissan-x-trail-01.jpg'],
    description: 'স্মার্ট অল-হুইল ড্রাইভ এবং প্যানোরামিক ভিউ সমৃদ্ধ রুচিশীল এসইউভি। পাহাড়ি পথ ও হাইওয়েতে অতুলনীয়।',
    status: 'available',
    assignedDriver: null,
    currentMileage: 58000,
  },
  {
    name: 'নিসান সানি সুপার স্যালুন ২০১৭',
    brand: 'Nissan',
    model: 'Sunny',
    registrationNumber: 'DHA-GA-11-2017',
    carType: 'sedan',
    year: 2017,
    seatingCapacity: 5,
    fuelType: 'cng',
    transmission: 'manual',
    dailyRentalPrice: 2800,
    images: ['/uploads/cars/nissan-sunny-01.jpg'],
    description: 'সাশ্রয়ী মূল্যে বাজেট ট্রিপের জন্য উপযোগী সিএনজি ও পেট্রোল চালিত নির্ভরযোগ্য সেডান কার।',
    status: 'available',
    assignedDriver: null,
    currentMileage: 76000,
  },
  {
    name: 'নিসান ক্যারাভান মাইক্রোবাস ২০১৫',
    brand: 'Nissan',
    model: 'Caravan',
    registrationNumber: 'DHA-CHA-51-2018',
    carType: 'microbus',
    year: 2015,
    seatingCapacity: 14,
    fuelType: 'diesel',
    transmission: 'manual',
    dailyRentalPrice: 7000,
    images: ['/uploads/cars/nissan-caravan-01.jpg'],
    description: '১৪ সিটের বড় ক্যাপাসিটির ক্যারাভান। গ্রুপ ইভেন্ট, বিয়ে ও দূরপাল্লার ট্যুরের জন্য আরামদায়ক বাহন।',
    status: 'available',
    assignedDriver: null,
    currentMileage: 98000,
  },
  {
    name: 'নিসান নাভারা ডাবল কেবিন ২০১৯',
    brand: 'Nissan',
    model: 'Navara',
    registrationNumber: 'DHA-THA-11-2019',
    carType: 'pickup',
    year: 2019,
    seatingCapacity: 5,
    fuelType: 'diesel',
    transmission: 'manual',
    dailyRentalPrice: 7200,
    images: ['/uploads/cars/nissan-navara-01.jpg'],
    description: 'উঁচু-নিচু রাস্তা ও প্রকল্পের কাজের জন্য অত্যন্ত বলিষ্ঠ ডাবল কেবিন ৪x৪ পিকআপ ভ্যান।',
    status: 'available',
    assignedDriver: null,
    currentMileage: 61000,
  },
  {
    name: 'মিতসুবিশি আউটল্যান্ডার ২০১৯',
    brand: 'Mitsubishi',
    model: 'Outlander',
    registrationNumber: 'DHA-GHA-13-2020',
    carType: 'suv',
    year: 2019,
    seatingCapacity: 7,
    fuelType: 'petrol',
    transmission: 'automatic',
    dailyRentalPrice: 6000,
    images: ['/uploads/cars/mitsubishi-outlander-01.jpg'],
    description: '৭ আসনের আধুনিক পারিবারিক এসইউভি। উন্নত সেফটি সেন্সর ও চমৎকার ড্রাইভিং আরাম।',
    status: 'available',
    assignedDriver: null,
    currentMileage: 47000,
  },
  {
    name: 'মিতসুবিশি পাজেরো স্পোর্ট ২০১৭',
    brand: 'Mitsubishi',
    model: 'Pajero Sport',
    registrationNumber: 'DHA-GHA-13-2021',
    carType: 'suv',
    year: 2017,
    seatingCapacity: 7,
    fuelType: 'diesel',
    transmission: 'automatic',
    dailyRentalPrice: 8500,
    images: ['/uploads/cars/mitsubishi-pajero-01.jpg'],
    description: 'কঠিন রাস্তা ও পাহাড়ি এলাকার জন্য সুপরিচিত শক্তিশালী ৭ সিটার ৪x৪ অফ-রোড এসইউভি।',
    status: 'available',
    assignedDriver: null,
    currentMileage: 71000,
  },
  {
    name: 'মিতসুবিশি এল২০০ পিকআপ ২০২১',
    brand: 'Mitsubishi',
    model: 'L200',
    registrationNumber: 'DHA-THA-11-2022',
    carType: 'pickup',
    year: 2021,
    seatingCapacity: 5,
    fuelType: 'diesel',
    transmission: 'manual',
    dailyRentalPrice: 7000,
    images: ['/uploads/cars/mitsubishi-l200-01.jpg'],
    description: 'প্রিমিয়াম আরামদায়ক ইন্টেরিয়র এবং দুর্দান্ত লোডিং ক্যাপাসিটি সমৃদ্ধ ডাবল কেবিন পিকআপ।',
    status: 'available',
    assignedDriver: null,
    currentMileage: 31000,
  },
  {
    name: 'সুজুকি সুইফট ২০২০',
    brand: 'Suzuki',
    model: 'Swift',
    registrationNumber: 'DHA-KHA-11-2023',
    carType: 'hatchback',
    year: 2020,
    seatingCapacity: 5,
    fuelType: 'petrol',
    transmission: 'automatic',
    dailyRentalPrice: 2600,
    images: ['/uploads/cars/suzuki-swift-01.jpg'],
    description: 'কমপ্যাক্ট ও আকর্ষণীয় লুকের জ্বালানি সাশ্রয়ী সিটি কার। দ্রুত ট্রাভেল ও সহজ ড্রাইভিং।',
    status: 'available',
    assignedDriver: null,
    currentMileage: 29000,
  },
  {
    name: 'সুজুকি ওয়াগন আর ২০১৮',
    brand: 'Suzuki',
    model: 'Wagon R',
    registrationNumber: 'DHA-KHA-11-2024',
    carType: 'hatchback',
    year: 2018,
    seatingCapacity: 4,
    fuelType: 'petrol',
    transmission: 'automatic',
    dailyRentalPrice: 2200,
    images: ['/uploads/cars/suzuki-wagon-r-01.jpg'],
    description: 'স্বল্প খরচে দৈনন্দিন যাতায়াত ও ছোট পরিবারের জন্য বাজেট-বান্ধব নির্ভরযোগ্য হ্যাচব্যাক।',
    status: 'available',
    assignedDriver: null,
    currentMileage: 44000,
  },
  {
    name: 'সুজুকি সিয়াজ ২০১৯',
    brand: 'Suzuki',
    model: 'Ciaz',
    registrationNumber: 'DHA-GA-11-2025',
    carType: 'sedan',
    year: 2019,
    seatingCapacity: 5,
    fuelType: 'petrol',
    transmission: 'manual',
    dailyRentalPrice: 3200,
    images: ['/uploads/cars/suzuki-ciaz-01.jpg'],
    description: 'পেছনের সিটে পর্যাপ্ত লেগরুম ও বড় বুট স্পেস সমৃদ্ধ আরামদায়ক মিড-লেভেল সেডান কার।',
    status: 'available',
    assignedDriver: null,
    currentMileage: 46000,
  },
  {
    name: 'সুজুকি ভিটারা ব্রেজা ২০২০',
    brand: 'Suzuki',
    model: 'Vitara Brezza',
    registrationNumber: 'DHA-GHA-13-2026',
    carType: 'suv',
    year: 2020,
    seatingCapacity: 5,
    fuelType: 'diesel',
    transmission: 'manual',
    dailyRentalPrice: 4000,
    images: ['/uploads/cars/suzuki-vitara-brezza-01.jpg'],
    description: 'কমপ্যাক্ট স্পোর্টস ইউটিলিটি ভেহিকেল (SUV)। রুচিশীল ডিজাইন ও দীর্ঘস্থায়ী স্থায়িত্ব।',
    status: 'available',
    assignedDriver: null,
    currentMileage: 38000,
  },
  {
    name: 'হুন্দাই টাকসন ২০২০',
    brand: 'Hyundai',
    model: 'Tucson',
    registrationNumber: 'DHA-GHA-13-2027',
    carType: 'suv',
    year: 2020,
    seatingCapacity: 5,
    fuelType: 'petrol',
    transmission: 'automatic',
    dailyRentalPrice: 5600,
    images: ['/uploads/cars/hyundai-tucson-01.jpg'],
    description: 'হাই-লেভেল সেফটি রেটিং, লেদার সিট ও আল্ট্রা-স্মুথ রাইডিং অফার করা প্রিমিয়াম এসইউভি।',
    status: 'available',
    assignedDriver: null,
    currentMileage: 33000,
  },
  {
    name: 'হুন্দাই ক্রিয়েটা ২০২১',
    brand: 'Hyundai',
    model: 'Creta',
    registrationNumber: 'DHA-GHA-13-2028',
    carType: 'suv',
    year: 2021,
    seatingCapacity: 5,
    fuelType: 'petrol',
    transmission: 'automatic',
    dailyRentalPrice: 4500,
    images: ['/uploads/cars/hyundai-creta-01.jpg'],
    description: 'ভেন্টিলেটেড সিট, সানরুফ ও ডিজিটাল ড্রাইভার ডিসপ্লেযুক্ত অন্যতম জনপ্রিয় আধুনিক এসইউভি।',
    status: 'available',
    assignedDriver: null,
    currentMileage: 26000,
  },
  {
    name: 'হুন্দাই এলানট্ৰা ২০১৯',
    brand: 'Hyundai',
    model: 'Elantra',
    registrationNumber: 'DHA-GA-11-2029',
    carType: 'sedan',
    year: 2019,
    seatingCapacity: 5,
    fuelType: 'octane',
    transmission: 'automatic',
    dailyRentalPrice: 4200,
    images: ['/uploads/cars/hyundai-elantra-01.jpg'],
    description: 'আধুনিক অ্যারোডাইনামিক বডি শেপ ও উন্নত ড্রাইভিং অ্যাসিস্ট্যান্ট ফিচার সমৃদ্ধ প্রিমিয়াম সেডান।',
    status: 'available',
    assignedDriver: null,
    currentMileage: 40000,
  },
  {
    name: 'হুন্দাই গ্র্যান্ড স্টারেক্স ২০১৮',
    brand: 'Hyundai',
    model: 'Grand Starex',
    registrationNumber: 'DHA-CHA-51-2030',
    carType: 'microbus',
    year: 2018,
    seatingCapacity: 11,
    fuelType: 'diesel',
    transmission: 'automatic',
    dailyRentalPrice: 6800,
    images: ['/uploads/cars/hyundai-grand-starex-01.jpg'],
    description: '১১ সিটের বিলাসবহুল এক্সিকিউটিভ ভ্যান। কর্পোরেট টিম ও পরিবারের দীর্ঘ ভ্রমণের জন্য সেরা পছন্দ।',
    status: 'available',
    assignedDriver: null,
    currentMileage: 59000,
  },
  {
    name: 'কিয়া স্পোর্টেজ ২০২০',
    brand: 'Kia',
    model: 'Sportage',
    registrationNumber: 'DHA-GHA-13-2031',
    carType: 'suv',
    year: 2020,
    seatingCapacity: 5,
    fuelType: 'petrol',
    transmission: 'automatic',
    dailyRentalPrice: 5800,
    images: ['/uploads/cars/kia-sportage-01.jpg'],
    description: 'বোল্ড এক্সটেরিয়র ডিজাইন ও প্রিমিয়াম অডিও সিস্টেমযুক্ত আরামদায়ক ও ট্রেন্ডি ৫ সিটার এসইউভি।',
    status: 'available',
    assignedDriver: null,
    currentMileage: 32000,
  },
  {
    name: 'কিয়া সেল্টোস ২০২১',
    brand: 'Kia',
    model: 'Seltos',
    registrationNumber: 'DHA-GHA-13-2032',
    carType: 'suv',
    year: 2021,
    seatingCapacity: 5,
    fuelType: 'petrol',
    transmission: 'automatic',
    dailyRentalPrice: 4600,
    images: ['/uploads/cars/kia-seltos-01.jpg'],
    description: 'আকর্ষণীয় এম্বিয়েন্ট লাইটিং, টাচস্ক্রিন ইনফোটেইনমেন্ট ও স্মুথ পিকআপের পারফেক্ট কমপ্যাক্ট এসইউভি।',
    status: 'available',
    assignedDriver: null,
    currentMileage: 25000,
  },
  {
    name: 'কিয়া কার্নিভাল ২০১৯',
    brand: 'Kia',
    model: 'Carnival',
    registrationNumber: 'DHA-CHA-51-2033',
    carType: 'microbus',
    year: 2019,
    seatingCapacity: 8,
    fuelType: 'diesel',
    transmission: 'automatic',
    dailyRentalPrice: 8000,
    images: ['/uploads/cars/kia-carnival-01.jpg'],
    description: 'আল্ট্রা-লাক্সারি ক্যাপ্টেন সিট, ডুয়েল সানরুফ ও ভিআইপি আরামদায়ক ভ্রমণের ৮ সিটার ফ্ল্যাগশিপ ভ্যান।',
    status: 'available',
    assignedDriver: null,
    currentMileage: 43000,
  },
  {
    name: 'টয়োটা করোলা ক্রস ২০২২',
    brand: 'Toyota',
    model: 'Corolla Cross',
    registrationNumber: 'DHA-GHA-13-2034',
    carType: 'suv',
    year: 2022,
    seatingCapacity: 5,
    fuelType: 'hybrid',
    transmission: 'automatic',
    dailyRentalPrice: 6200,
    images: ['/uploads/cars/toyota-corolla-cross-01.jpg'],
    description: 'লেটেস্ট মডেলের হাইব্রিড ক্রসওভার এসইউভি। সর্বোচ্চ ফুয়েল এফিশিয়েন্সি ও অত্যাধুনিক নিরাপত্তা ফিচার।',
    status: 'available',
    assignedDriver: null,
    currentMileage: 18000,
  },
  {
    name: 'মাজদা সিএক্স-৫ ২০১৯',
    brand: 'Mazda',
    model: 'CX-5',
    registrationNumber: 'DHA-GHA-13-2035',
    carType: 'suv',
    year: 2019,
    seatingCapacity: 5,
    fuelType: 'petrol',
    transmission: 'automatic',
    dailyRentalPrice: 5400,
    images: ['/uploads/cars/mazda-cx-5-01.jpg'],
    description: 'জাপানি প্রিমিয়াম ক্রাফটসম্যানশিপ, চমৎকার এক্সিলারেশন ও প্রিমিয়াম কোয়ালিটি ইন্টেরিয়রের এসইউভি।',
    status: 'available',
    assignedDriver: null,
    currentMileage: 37000,
  },
];

const seedCars = async () => {
  let created = 0;
  let skipped = 0;

  const drivers = await Driver.find({ status: 'available' });

  let index = 0;
  for (const car of carData) {
    const existingCar = await Car.findOne({
      registrationNumber: car.registrationNumber.toUpperCase(),
    });

    const driverToAssign = drivers.length > 0 ? drivers[index % drivers.length]._id : null;
    index++;

    if (existingCar) {
      existingCar.images = car.images;
      if (!existingCar.assignedDriver && driverToAssign) {
        existingCar.assignedDriver = driverToAssign;
      }
      await existingCar.save();
      skipped++;
      continue;
    }

    await Car.create({
      name: car.name,
      brand: car.brand,
      model: car.model,
      registrationNumber: car.registrationNumber,
      carType: car.carType,
      year: car.year,
      seatingCapacity: car.seatingCapacity,
      fuelType: car.fuelType,
      transmission: car.transmission,
      dailyRentalPrice: car.dailyRentalPrice,
      images: car.images,
      description: car.description,
      status: 'available',
      assignedDriver: driverToAssign,
      currentMileage: car.currentMileage,
    });

    created++;
  }

  console.log(`Cars seeded: ${created} created, ${skipped} skipped (assigned drivers updated).`);
};

module.exports = seedCars;
