const bcrypt = require('bcryptjs');
const User = require('../models/User');
const Driver = require('../models/Driver');

// Demo profile images (35 individual realistic driver portrait images)
const DEMO_PROFILE_IMAGES = [
  'uploads/profiles/drivers/driver_01.jpg',
  'uploads/profiles/drivers/driver_02.jpg',
  'uploads/profiles/drivers/driver_03.jpg',
  'uploads/profiles/drivers/driver_04.jpg',
  'uploads/profiles/drivers/driver_05.jpg',
  'uploads/profiles/drivers/driver_06.jpg',
  'uploads/profiles/drivers/driver_07.jpg',
  'uploads/profiles/drivers/driver_08.jpg',
  'uploads/profiles/drivers/driver_09.jpg',
  'uploads/profiles/drivers/driver_10.jpg',
  'uploads/profiles/drivers/driver_11.jpg',
  'uploads/profiles/drivers/driver_12.jpg',
  'uploads/profiles/drivers/driver_13.jpg',
  'uploads/profiles/drivers/driver_14.jpg',
  'uploads/profiles/drivers/driver_15.jpg',
  'uploads/profiles/drivers/driver_16.jpg',
  'uploads/profiles/drivers/driver_17.jpg',
  'uploads/profiles/drivers/driver_18.jpg',
  'uploads/profiles/drivers/driver_19.jpg',
  'uploads/profiles/drivers/driver_20.jpg',
  'uploads/profiles/drivers/driver_21.jpg',
  'uploads/profiles/drivers/driver_22.jpg',
  'uploads/profiles/drivers/driver_23.jpg',
  'uploads/profiles/drivers/driver_24.jpg',
  'uploads/profiles/drivers/driver_25.jpg',
  'uploads/profiles/drivers/driver_26.jpg',
  'uploads/profiles/drivers/driver_27.jpg',
  'uploads/profiles/drivers/driver_28.jpg',
  'uploads/profiles/drivers/driver_29.jpg',
  'uploads/profiles/drivers/driver_30.jpg',
  'uploads/profiles/drivers/driver_31.jpg',
  'uploads/profiles/drivers/driver_32.jpg',
  'uploads/profiles/drivers/driver_33.jpg',
  'uploads/profiles/drivers/driver_34.jpg',
  'uploads/profiles/drivers/driver_35.jpg',
];

// 35 realistic Bangladeshi driver demo records
const driverData = [
  {
    user: {
      name: 'মোহাম্মদ রফিকুল ইসলাম',
      email: 'driver01@gari-lagbe.com',
      phone: '01711-001001',
      password: 'Driver@12345',
    },
    driver: {
      fullName: 'মোহাম্মদ রফিকুল ইসলাম',
      phone: '01711-001001',
      email: 'driver01@gari-lagbe.com',
      profileImage: DEMO_PROFILE_IMAGES[0],
      dateOfBirth: new Date('1985-03-12'),
      address: { street: '৪৫ মিরপুর রোড', city: 'ঢাকা', district: 'ঢাকা', postalCode: '1216' },
      licenseNumber: 'DL-DHK-2010-001001',
      licenseExpiryDate: new Date('2027-03-31'),
      experienceYears: 12,
      status: 'available',
      rating: 4.7,
      totalTrips: 320,
      emergencyContact: { name: 'সালমা বেগম', phone: '01911-001001', relationship: 'স্ত্রী' },
    },
  },
  {
    user: {
      name: 'আবদুল করিম',
      email: 'driver02@gari-lagbe.com',
      phone: '01712-002002',
      password: 'Driver@12345',
    },
    driver: {
      fullName: 'আবদুল করিম',
      phone: '01712-002002',
      email: 'driver02@gari-lagbe.com',
      profileImage: DEMO_PROFILE_IMAGES[1],
      dateOfBirth: new Date('1990-07-25'),
      address: { street: '১২ গুলশান অ্যাভিনিউ', city: 'ঢাকা', district: 'ঢাকা', postalCode: '1212' },
      licenseNumber: 'DL-DHK-2015-002002',
      licenseExpiryDate: new Date('2028-07-31'),
      experienceYears: 8,
      status: 'available',
      rating: 4.5,
      totalTrips: 210,
      emergencyContact: { name: 'করিম উদ্দিন', phone: '01912-002002', relationship: 'বাবা' },
    },
  },
  {
    user: {
      name: 'মোঃ জাহাঙ্গীর আলম',
      email: 'driver03@gari-lagbe.com',
      phone: '01713-003003',
      password: 'Driver@12345',
    },
    driver: {
      fullName: 'মোঃ জাহাঙ্গীর আলম',
      phone: '01713-003003',
      email: 'driver03@gari-lagbe.com',
      profileImage: DEMO_PROFILE_IMAGES[2],
      dateOfBirth: new Date('1988-11-05'),
      address: { street: '৭৮ উত্তরা সেক্টর ৭', city: 'ঢাকা', district: 'ঢাকা', postalCode: '1230' },
      licenseNumber: 'DL-DHK-2012-003003',
      licenseExpiryDate: new Date('2026-11-30'),
      experienceYears: 10,
      status: 'available',
      rating: 4.6,
      totalTrips: 275,
      emergencyContact: { name: 'রহিমা বেগম', phone: '01913-003003', relationship: 'মা' },
    },
  },
  {
    user: {
      name: 'সিরাজুল হক',
      email: 'driver04@gari-lagbe.com',
      phone: '01714-004004',
      password: 'Driver@12345',
    },
    driver: {
      fullName: 'সিরাজুল হক',
      phone: '01714-004004',
      email: 'driver04@gari-lagbe.com',
      profileImage: DEMO_PROFILE_IMAGES[3],
      dateOfBirth: new Date('1983-01-18'),
      address: { street: '২৩ আগ্রাবাদ কমার্শিয়াল এলাকা', city: 'চট্টগ্রাম', district: 'চট্টগ্রাম', postalCode: '4100' },
      licenseNumber: 'DL-CTG-2008-004004',
      licenseExpiryDate: new Date('2027-01-31'),
      experienceYears: 15,
      status: 'available',
      rating: 4.8,
      totalTrips: 450,
      emergencyContact: { name: 'নাসরিন হক', phone: '01914-004004', relationship: 'স্ত্রী' },
    },
  },
  {
    user: {
      name: 'মোহাম্মদ সাইফুল ইসলাম',
      email: 'driver05@gari-lagbe.com',
      phone: '01715-005005',
      password: 'Driver@12345',
    },
    driver: {
      fullName: 'মোহাম্মদ সাইফুল ইসলাম',
      phone: '01715-005005',
      email: 'driver05@gari-lagbe.com',
      profileImage: DEMO_PROFILE_IMAGES[4],
      dateOfBirth: new Date('1992-05-30'),
      address: { street: '৫৬ সোনাদিয়া রোড', city: 'কক্সবাজার', district: 'কক্সবাজার', postalCode: '4700' },
      licenseNumber: 'DL-COX-2017-005005',
      licenseExpiryDate: new Date('2028-05-31'),
      experienceYears: 6,
      status: 'available',
      rating: 4.3,
      totalTrips: 140,
      emergencyContact: { name: 'আমিনুল ইসলাম', phone: '01915-005005', relationship: 'ভাই' },
    },
  },
  {
    user: {
      name: 'মোঃ আনিসুর রহমান',
      email: 'driver06@gari-lagbe.com',
      phone: '01716-006006',
      password: 'Driver@12345',
    },
    driver: {
      fullName: 'মোঃ আনিসুর রহমান',
      phone: '01716-006006',
      email: 'driver06@gari-lagbe.com',
      profileImage: DEMO_PROFILE_IMAGES[0],
      dateOfBirth: new Date('1987-09-14'),
      address: { street: '৩৪ বন্দর রোড', city: 'নারায়ণগঞ্জ', district: 'নারায়ণগঞ্জ', postalCode: '1400' },
      licenseNumber: 'DL-NAR-2011-006006',
      licenseExpiryDate: new Date('2027-09-30'),
      experienceYears: 11,
      status: 'available',
      rating: 4.4,
      totalTrips: 290,
      emergencyContact: { name: 'ফাতেমা বেগম', phone: '01916-006006', relationship: 'স্ত্রী' },
    },
  },
  {
    user: {
      name: 'হাসান আলী',
      email: 'driver07@gari-lagbe.com',
      phone: '01717-007007',
      password: 'Driver@12345',
    },
    driver: {
      fullName: 'হাসান আলী',
      phone: '01717-007007',
      email: 'driver07@gari-lagbe.com',
      profileImage: DEMO_PROFILE_IMAGES[1],
      dateOfBirth: new Date('1991-02-22'),
      address: { street: '৮৯ বগুড়া সড়ক', city: 'রাজশাহী', district: 'রাজশাহী', postalCode: '6000' },
      licenseNumber: 'DL-RAJ-2016-007007',
      licenseExpiryDate: new Date('2028-02-28'),
      experienceYears: 7,
      status: 'available',
      rating: 4.2,
      totalTrips: 175,
      emergencyContact: { name: 'আলী হোসেন', phone: '01917-007007', relationship: 'বাবা' },
    },
  },
  {
    user: {
      name: 'মোহাম্মদ ইউসুফ মিয়া',
      email: 'driver08@gari-lagbe.com',
      phone: '01718-008008',
      password: 'Driver@12345',
    },
    driver: {
      fullName: 'মোহাম্মদ ইউসুফ মিয়া',
      phone: '01718-008008',
      email: 'driver08@gari-lagbe.com',
      profileImage: DEMO_PROFILE_IMAGES[2],
      dateOfBirth: new Date('1984-06-08'),
      address: { street: '১৫ খুলনা রোড', city: 'খুলনা', district: 'খুলনা', postalCode: '9100' },
      licenseNumber: 'DL-KHU-2009-008008',
      licenseExpiryDate: new Date('2026-06-30'),
      experienceYears: 14,
      status: 'available',
      rating: 4.9,
      totalTrips: 520,
      emergencyContact: { name: 'মরিয়ম বেগম', phone: '01918-008008', relationship: 'স্ত্রী' },
    },
  },
  {
    user: {
      name: 'শফিকুল ইসলাম',
      email: 'driver09@gari-lagbe.com',
      phone: '01719-009009',
      password: 'Driver@12345',
    },
    driver: {
      fullName: 'শফিকুল ইসলাম',
      phone: '01719-009009',
      email: 'driver09@gari-lagbe.com',
      profileImage: DEMO_PROFILE_IMAGES[3],
      dateOfBirth: new Date('1989-12-03'),
      address: { street: '৬৭ মৌলভীবাজার রোড', city: 'সিলেট', district: 'সিলেট', postalCode: '3100' },
      licenseNumber: 'DL-SYL-2013-009009',
      licenseExpiryDate: new Date('2027-12-31'),
      experienceYears: 9,
      status: 'available',
      rating: 4.5,
      totalTrips: 230,
      emergencyContact: { name: 'ইসলাম উদ্দিন', phone: '01919-009009', relationship: 'ভাই' },
    },
  },
  {
    user: {
      name: 'মোঃ তারিকুল ইসলাম',
      email: 'driver10@gari-lagbe.com',
      phone: '01720-010010',
      password: 'Driver@12345',
    },
    driver: {
      fullName: 'মোঃ তারিকুল ইসলাম',
      phone: '01720-010010',
      email: 'driver10@gari-lagbe.com',
      profileImage: DEMO_PROFILE_IMAGES[4],
      dateOfBirth: new Date('1993-08-17'),
      address: { street: '৪১ ময়মনসিংহ রোড', city: 'ময়মনসিংহ', district: 'ময়মনসিংহ', postalCode: '2200' },
      licenseNumber: 'DL-MYM-2018-010010',
      licenseExpiryDate: new Date('2029-08-31'),
      experienceYears: 5,
      status: 'available',
      rating: 4.1,
      totalTrips: 110,
      emergencyContact: { name: 'তাহেরা বেগম', phone: '01821-010010', relationship: 'মা' },
    },
  },
  {
    user: {
      name: 'নুরুল আমিন',
      email: 'driver11@gari-lagbe.com',
      phone: '01721-011011',
      password: 'Driver@12345',
    },
    driver: {
      fullName: 'নুরুল আমিন',
      phone: '01721-011011',
      email: 'driver11@gari-lagbe.com',
      profileImage: DEMO_PROFILE_IMAGES[0],
      dateOfBirth: new Date('1986-04-28'),
      address: { street: '৯ কুমিল্লা সদর', city: 'কুমিল্লা', district: 'কুমিল্লা', postalCode: '3500' },
      licenseNumber: 'DL-CUM-2010-011011',
      licenseExpiryDate: new Date('2027-04-30'),
      experienceYears: 13,
      status: 'available',
      rating: 4.6,
      totalTrips: 380,
      emergencyContact: { name: 'আমিনুল হক', phone: '01922-011011', relationship: 'বাবা' },
    },
  },
  {
    user: {
      name: 'মোহাম্মদ জামাল উদ্দিন',
      email: 'driver12@gari-lagbe.com',
      phone: '01722-012012',
      password: 'Driver@12345',
    },
    driver: {
      fullName: 'মোহাম্মদ জামাল উদ্দিন',
      phone: '01722-012012',
      email: 'driver12@gari-lagbe.com',
      profileImage: DEMO_PROFILE_IMAGES[1],
      dateOfBirth: new Date('1994-10-10'),
      address: { street: '৫২ যশোর রোড', city: 'যশোর', district: 'যশোর', postalCode: '7400' },
      licenseNumber: 'DL-JES-2019-012012',
      licenseExpiryDate: new Date('2029-10-31'),
      experienceYears: 4,
      status: 'available',
      rating: 4.0,
      totalTrips: 88,
      emergencyContact: { name: 'জামিলা খানম', phone: '01923-012012', relationship: 'স্ত্রী' },
    },
  },
  {
    user: {
      name: 'আবুল কাশেম',
      email: 'driver13@gari-lagbe.com',
      phone: '01723-013013',
      password: 'Driver@12345',
    },
    driver: {
      fullName: 'আবুল কাশেম',
      phone: '01723-013013',
      email: 'driver13@gari-lagbe.com',
      profileImage: DEMO_PROFILE_IMAGES[2],
      dateOfBirth: new Date('1982-07-07'),
      address: { street: '২৮ রংপুর সড়ক', city: 'রংপুর', district: 'রংপুর', postalCode: '5400' },
      licenseNumber: 'DL-RAN-2007-013013',
      licenseExpiryDate: new Date('2026-07-31'),
      experienceYears: 16,
      status: 'available',
      rating: 4.8,
      totalTrips: 600,
      emergencyContact: { name: 'হামিদা বেগম', phone: '01924-013013', relationship: 'স্ত্রী' },
    },
  },
  {
    user: {
      name: 'মোঃ মাহমুদুল হাসান',
      email: 'driver14@gari-lagbe.com',
      phone: '01724-014014',
      password: 'Driver@12345',
    },
    driver: {
      fullName: 'মোঃ মাহমুদুল হাসান',
      phone: '01724-014014',
      email: 'driver14@gari-lagbe.com',
      profileImage: DEMO_PROFILE_IMAGES[3],
      dateOfBirth: new Date('1995-01-15'),
      address: { street: '৬৩ বরিশাল রোড', city: 'বরিশাল', district: 'বরিশাল', postalCode: '8200' },
      licenseNumber: 'DL-BAR-2020-014014',
      licenseExpiryDate: new Date('2030-01-31'),
      experienceYears: 3,
      status: 'available',
      rating: 3.9,
      totalTrips: 65,
      emergencyContact: { name: 'হাসান মিয়া', phone: '01925-014014', relationship: 'বাবা' },
    },
  },
  {
    user: {
      name: 'মোহাম্মদ আলাউদ্দিন',
      email: 'driver15@gari-lagbe.com',
      phone: '01725-015015',
      password: 'Driver@12345',
    },
    driver: {
      fullName: 'মোহাম্মদ আলাউদ্দিন',
      phone: '01725-015015',
      email: 'driver15@gari-lagbe.com',
      profileImage: DEMO_PROFILE_IMAGES[4],
      dateOfBirth: new Date('1980-09-21'),
      address: { street: '১৮ ফরিদপুর সদর', city: 'ফরিদপুর', district: 'ফরিদপুর', postalCode: '7800' },
      licenseNumber: 'DL-FAR-2005-015015',
      licenseExpiryDate: new Date('2027-09-30'),
      experienceYears: 18,
      status: 'available',
      rating: 4.9,
      totalTrips: 720,
      emergencyContact: { name: 'আলেয়া বেগম', phone: '01926-015015', relationship: 'স্ত্রী' },
    },
  },
  // Drivers 16–35: Additional drivers from across Bangladesh
  {
    user: {
      name: 'মোঃ কামরুল হাসান',
      email: 'driver16@gari-lagbe.com',
      phone: '01726-016016',
      password: 'Driver@12345',
    },
    driver: {
      fullName: 'মোঃ কামরুল হাসান',
      phone: '01726-016016',
      email: 'driver16@gari-lagbe.com',
      profileImage: DEMO_PROFILE_IMAGES[5],
      dateOfBirth: new Date('1993-04-05'),
      address: { street: '৩৬ নওগাঁ সদর', city: 'নওগাঁ', district: 'নওগাঁ', postalCode: '6500' },
      licenseNumber: 'DL-NOG-2018-016016',
      licenseExpiryDate: new Date('2028-04-30'),
      experienceYears: 5,
      status: 'available',
      rating: 4.2,
      totalTrips: 130,
      emergencyContact: { name: 'কামরুন্নাহার', phone: '01927-016016', relationship: 'স্ত্রী' },
    },
  },
  {
    user: {
      name: 'আবদুল মান্নান',
      email: 'driver17@gari-lagbe.com',
      phone: '01727-017017',
      password: 'Driver@12345',
    },
    driver: {
      fullName: 'আবদুল মান্নান',
      phone: '01727-017017',
      email: 'driver17@gari-lagbe.com',
      profileImage: DEMO_PROFILE_IMAGES[6],
      dateOfBirth: new Date('1981-08-19'),
      address: { street: '২২ সিরাজগঞ্জ সদর', city: 'সিরাজগঞ্জ', district: 'সিরাজগঞ্জ', postalCode: '6700' },
      licenseNumber: 'DL-SIR-2006-017017',
      licenseExpiryDate: new Date('2026-08-31'),
      experienceYears: 17,
      status: 'available',
      rating: 4.7,
      totalTrips: 490,
      emergencyContact: { name: 'মান্নান মিয়া', phone: '01928-017017', relationship: 'বাবা' },
    },
  },
  {
    user: {
      name: 'মোহাম্মদ আরিফুল ইসলাম',
      email: 'driver18@gari-lagbe.com',
      phone: '01728-018018',
      password: 'Driver@12345',
    },
    driver: {
      fullName: 'মোহাম্মদ আরিফুল ইসলাম',
      phone: '01728-018018',
      email: 'driver18@gari-lagbe.com',
      profileImage: DEMO_PROFILE_IMAGES[7],
      dateOfBirth: new Date('1998-12-10'),
      address: { street: '৪৮ পাবনা সদর', city: 'পাবনা', district: 'পাবনা', postalCode: '6600' },
      licenseNumber: 'DL-PAB-2021-018018',
      licenseExpiryDate: new Date('2031-12-31'),
      experienceYears: 2,
      status: 'available',
      rating: 3.8,
      totalTrips: 45,
      emergencyContact: { name: 'আরিফা বেগম', phone: '01929-018018', relationship: 'মা' },
    },
  },
  {
    user: {
      name: 'মোঃ জুলফিকার আলী',
      email: 'driver19@gari-lagbe.com',
      phone: '01729-019019',
      password: 'Driver@12345',
    },
    driver: {
      fullName: 'মোঃ জুলফিকার আলী',
      phone: '01729-019019',
      email: 'driver19@gari-lagbe.com',
      profileImage: DEMO_PROFILE_IMAGES[8],
      dateOfBirth: new Date('1979-06-14'),
      address: { street: '৭ চাঁপাইনবাবগঞ্জ সদর', city: 'চাঁপাইনবাবগঞ্জ', district: 'চাঁপাইনবাবগঞ্জ', postalCode: '6300' },
      licenseNumber: 'DL-CHA-2004-019019',
      licenseExpiryDate: new Date('2027-06-30'),
      experienceYears: 20,
      status: 'available',
      rating: 4.9,
      totalTrips: 850,
      emergencyContact: { name: 'জুলেখা বেগম', phone: '01931-019019', relationship: 'স্ত্রী' },
    },
  },
  {
    user: {
      name: 'রবিউল ইসলাম',
      email: 'driver20@gari-lagbe.com',
      phone: '01730-020020',
      password: 'Driver@12345',
    },
    driver: {
      fullName: 'রবিউল ইসলাম',
      phone: '01730-020020',
      email: 'driver20@gari-lagbe.com',
      profileImage: DEMO_PROFILE_IMAGES[9],
      dateOfBirth: new Date('1991-03-22'),
      address: { street: '৩১ নাটোর সদর', city: 'নাটোর', district: 'নাটোর', postalCode: '6400' },
      licenseNumber: 'DL-NAT-2016-020020',
      licenseExpiryDate: new Date('2028-03-31'),
      experienceYears: 7,
      status: 'available',
      rating: 4.3,
      totalTrips: 195,
      emergencyContact: { name: 'রাবেয়া বেগম', phone: '01932-020020', relationship: 'স্ত্রী' },
    },
  },
  {
    user: {
      name: 'মোহাম্মদ শাহাবুদ্দিন',
      email: 'driver21@gari-lagbe.com',
      phone: '01731-021021',
      password: 'Driver@12345',
    },
    driver: {
      fullName: 'মোহাম্মদ শাহাবুদ্দিন',
      phone: '01731-021021',
      email: 'driver21@gari-lagbe.com',
      profileImage: DEMO_PROFILE_IMAGES[0],
      dateOfBirth: new Date('1986-10-08'),
      address: { street: '৫৯ বগুড়া সদর', city: 'বগুড়া', district: 'বগুড়া', postalCode: '5800' },
      licenseNumber: 'DL-BOG-2011-021021',
      licenseExpiryDate: new Date('2027-10-31'),
      experienceYears: 12,
      status: 'available',
      rating: 4.5,
      totalTrips: 340,
      emergencyContact: { name: 'শাহেদা বেগম', phone: '01933-021021', relationship: 'স্ত্রী' },
    },
  },
  {
    user: {
      name: 'মোঃ আনোয়ার হোসেন',
      email: 'driver22@gari-lagbe.com',
      phone: '01732-022022',
      password: 'Driver@12345',
    },
    driver: {
      fullName: 'মোঃ আনোয়ার হোসেন',
      phone: '01732-022022',
      email: 'driver22@gari-lagbe.com',
      profileImage: DEMO_PROFILE_IMAGES[1],
      dateOfBirth: new Date('1984-01-30'),
      address: { street: '১৩ জয়পুরহাট সদর', city: 'জয়পুরহাট', district: 'জয়পুরহাট', postalCode: '5900' },
      licenseNumber: 'DL-JOY-2009-022022',
      licenseExpiryDate: new Date('2027-01-31'),
      experienceYears: 14,
      status: 'available',
      rating: 4.6,
      totalTrips: 420,
      emergencyContact: { name: 'আনোয়ারা বেগম', phone: '01934-022022', relationship: 'স্ত্রী' },
    },
  },
  {
    user: {
      name: 'তৌহিদুল ইসলাম',
      email: 'driver23@gari-lagbe.com',
      phone: '01733-023023',
      password: 'Driver@12345',
    },
    driver: {
      fullName: 'তৌহিদুল ইসলাম',
      phone: '01733-023023',
      email: 'driver23@gari-lagbe.com',
      profileImage: DEMO_PROFILE_IMAGES[2],
      dateOfBirth: new Date('1995-07-11'),
      address: { street: '৪২ মাগুরা সদর', city: 'মাগুরা', district: 'মাগুরা', postalCode: '7600' },
      licenseNumber: 'DL-MAG-2019-023023',
      licenseExpiryDate: new Date('2029-07-31'),
      experienceYears: 4,
      status: 'available',
      rating: 4.0,
      totalTrips: 95,
      emergencyContact: { name: 'তাহমিনা বেগম', phone: '01935-023023', relationship: 'মা' },
    },
  },
  {
    user: {
      name: 'মোহাম্মদ হারুনুর রশিদ',
      email: 'driver24@gari-lagbe.com',
      phone: '01734-024024',
      password: 'Driver@12345',
    },
    driver: {
      fullName: 'মোহাম্মদ হারুনুর রশিদ',
      phone: '01734-024024',
      email: 'driver24@gari-lagbe.com',
      profileImage: DEMO_PROFILE_IMAGES[3],
      dateOfBirth: new Date('1977-11-25'),
      address: { street: '৬ নড়াইল সদর', city: 'নড়াইল', district: 'নড়াইল', postalCode: '7500' },
      licenseNumber: 'DL-NOR-2002-024024',
      licenseExpiryDate: new Date('2026-11-30'),
      experienceYears: 22,
      status: 'available',
      rating: 4.8,
      totalTrips: 970,
      emergencyContact: { name: 'রহিমা বেগম', phone: '01936-024024', relationship: 'স্ত্রী' },
    },
  },
  {
    user: {
      name: 'মোঃ সালাউদ্দিন',
      email: 'driver25@gari-lagbe.com',
      phone: '01735-025025',
      password: 'Driver@12345',
    },
    driver: {
      fullName: 'মোঃ সালাউদ্দিন',
      phone: '01735-025025',
      email: 'driver25@gari-lagbe.com',
      profileImage: DEMO_PROFILE_IMAGES[4],
      dateOfBirth: new Date('1990-05-03'),
      address: { street: '২৭ সাতক্ষীরা সদর', city: 'সাতক্ষীরা', district: 'সাতক্ষীরা', postalCode: '9400' },
      licenseNumber: 'DL-SAT-2015-025025',
      licenseExpiryDate: new Date('2028-05-31'),
      experienceYears: 8,
      status: 'available',
      rating: 4.4,
      totalTrips: 250,
      emergencyContact: { name: 'সালমা বেগম', phone: '01937-025025', relationship: 'স্ত্রী' },
    },
  },
  {
    user: {
      name: 'আবুল হোসেন মিয়া',
      email: 'driver26@gari-lagbe.com',
      phone: '01736-026026',
      password: 'Driver@12345',
    },
    driver: {
      fullName: 'আবুল হোসেন মিয়া',
      phone: '01736-026026',
      email: 'driver26@gari-lagbe.com',
      profileImage: DEMO_PROFILE_IMAGES[5],
      dateOfBirth: new Date('1982-02-17'),
      address: { street: '৫১ মেহেরপুর সদর', city: 'মেহেরপুর', district: 'মেহেরপুর', postalCode: '7100' },
      licenseNumber: 'DL-MEH-2007-026026',
      licenseExpiryDate: new Date('2026-02-28'),
      experienceYears: 16,
      status: 'available',
      rating: 4.7,
      totalTrips: 560,
      emergencyContact: { name: 'হোসেনারা বেগম', phone: '01938-026026', relationship: 'স্ত্রী' },
    },
  },
  {
    user: {
      name: 'মোহাম্মদ মোস্তাফিজুর রহমান',
      email: 'driver27@gari-lagbe.com',
      phone: '01737-027027',
      password: 'Driver@12345',
    },
    driver: {
      fullName: 'মোহাম্মদ মোস্তাফিজুর রহমান',
      phone: '01737-027027',
      email: 'driver27@gari-lagbe.com',
      profileImage: DEMO_PROFILE_IMAGES[6],
      dateOfBirth: new Date('1989-09-06'),
      address: { street: '১৯ কুষ্টিয়া সদর', city: 'কুষ্টিয়া', district: 'কুষ্টিয়া', postalCode: '7000' },
      licenseNumber: 'DL-KUS-2014-027027',
      licenseExpiryDate: new Date('2028-09-30'),
      experienceYears: 9,
      status: 'available',
      rating: 4.3,
      totalTrips: 280,
      emergencyContact: { name: 'মোস্তফা মিয়া', phone: '01939-027027', relationship: 'বাবা' },
    },
  },
  {
    user: {
      name: 'মোঃ জসিম উদ্দিন',
      email: 'driver28@gari-lagbe.com',
      phone: '01738-028028',
      password: 'Driver@12345',
    },
    driver: {
      fullName: 'মোঃ জসিম উদ্দিন',
      phone: '01738-028028',
      email: 'driver28@gari-lagbe.com',
      profileImage: DEMO_PROFILE_IMAGES[7],
      dateOfBirth: new Date('1997-01-28'),
      address: { street: '৬৪ চুয়াডাঙ্গা সদর', city: 'চুয়াডাঙ্গা', district: 'চুয়াডাঙ্গা', postalCode: '7200' },
      licenseNumber: 'DL-CHU-2020-028028',
      licenseExpiryDate: new Date('2030-01-31'),
      experienceYears: 3,
      status: 'available',
      rating: 3.9,
      totalTrips: 72,
      emergencyContact: { name: 'জহুরা বেগম', phone: '01941-028028', relationship: 'মা' },
    },
  },
  {
    user: {
      name: 'মোহাম্মদ রুহুল আমিন',
      email: 'driver29@gari-lagbe.com',
      phone: '01739-029029',
      password: 'Driver@12345',
    },
    driver: {
      fullName: 'মোহাম্মদ রুহুল আমিন',
      phone: '01739-029029',
      email: 'driver29@gari-lagbe.com',
      profileImage: DEMO_PROFILE_IMAGES[8],
      dateOfBirth: new Date('1983-07-15'),
      address: { street: '৩৩ ঝালকাঠি সদর', city: 'ঝালকাঠি', district: 'ঝালকাঠি', postalCode: '8400' },
      licenseNumber: 'DL-JHA-2008-029029',
      licenseExpiryDate: new Date('2027-07-31'),
      experienceYears: 15,
      status: 'available',
      rating: 4.6,
      totalTrips: 480,
      emergencyContact: { name: 'রুমানা বেগম', phone: '01942-029029', relationship: 'স্ত্রী' },
    },
  },
  {
    user: {
      name: 'মোঃ ফরিদুল ইসলাম',
      email: 'driver30@gari-lagbe.com',
      phone: '01740-030030',
      password: 'Driver@12345',
    },
    driver: {
      fullName: 'মোঃ ফরিদুল ইসলাম',
      phone: '01740-030030',
      email: 'driver30@gari-lagbe.com',
      profileImage: DEMO_PROFILE_IMAGES[9],
      dateOfBirth: new Date('1994-11-20'),
      address: { street: '৮ পিরোজপুর সদর', city: 'পিরোজপুর', district: 'পিরোজপুর', postalCode: '8500' },
      licenseNumber: 'DL-PIR-2019-030030',
      licenseExpiryDate: new Date('2029-11-30'),
      experienceYears: 4,
      status: 'available',
      rating: 4.1,
      totalTrips: 105,
      emergencyContact: { name: 'ফরিদা বেগম', phone: '01943-030030', relationship: 'স্ত্রী' },
    },
  },
  {
    user: {
      name: 'আলাল উদ্দিন',
      email: 'driver31@gari-lagbe.com',
      phone: '01741-031031',
      password: 'Driver@12345',
    },
    driver: {
      fullName: 'আলাল উদ্দিন',
      phone: '01741-031031',
      email: 'driver31@gari-lagbe.com',
      profileImage: DEMO_PROFILE_IMAGES[0],
      dateOfBirth: new Date('1988-04-12'),
      address: { street: '৪৫ বান্দরবান সদর', city: 'বান্দরবান', district: 'বান্দরবান', postalCode: '4600' },
      licenseNumber: 'DL-BAN-2013-031031',
      licenseExpiryDate: new Date('2028-04-30'),
      experienceYears: 10,
      status: 'available',
      rating: 4.4,
      totalTrips: 305,
      emergencyContact: { name: 'আলেয়া বেগম', phone: '01944-031031', relationship: 'স্ত্রী' },
    },
  },
  {
    user: {
      name: 'মোহাম্মদ ইব্রাহিম খলিল',
      email: 'driver32@gari-lagbe.com',
      phone: '01742-032032',
      password: 'Driver@12345',
    },
    driver: {
      fullName: 'মোহাম্মদ ইব্রাহিম খলিল',
      phone: '01742-032032',
      email: 'driver32@gari-lagbe.com',
      profileImage: DEMO_PROFILE_IMAGES[1],
      dateOfBirth: new Date('1980-08-27'),
      address: { street: '৩০ খাগড়াছড়ি সদর', city: 'খাগড়াছড়ি', district: 'খাগড়াছড়ি', postalCode: '4400' },
      licenseNumber: 'DL-KHA-2005-032032',
      licenseExpiryDate: new Date('2026-08-31'),
      experienceYears: 18,
      status: 'available',
      rating: 4.8,
      totalTrips: 670,
      emergencyContact: { name: 'খদিজা বেগম', phone: '01945-032032', relationship: 'স্ত্রী' },
    },
  },
  {
    user: {
      name: 'মোঃ শরিফুল হক',
      email: 'driver33@gari-lagbe.com',
      phone: '01743-033033',
      password: 'Driver@12345',
    },
    driver: {
      fullName: 'মোঃ শরিফুল হক',
      phone: '01743-033033',
      email: 'driver33@gari-lagbe.com',
      profileImage: DEMO_PROFILE_IMAGES[2],
      dateOfBirth: new Date('1992-02-09'),
      address: { street: '১৬ রাঙামাটি সদর', city: 'রাঙামাটি', district: 'রাঙামাটি', postalCode: '4500' },
      licenseNumber: 'DL-RNG-2017-033033',
      licenseExpiryDate: new Date('2028-02-28'),
      experienceYears: 6,
      status: 'available',
      rating: 4.2,
      totalTrips: 160,
      emergencyContact: { name: 'শরিফা বেগম', phone: '01946-033033', relationship: 'স্ত্রী' },
    },
  },
  {
    user: {
      name: 'মোহাম্মদ নজরুল ইসলাম',
      email: 'driver34@gari-lagbe.com',
      phone: '01744-034034',
      password: 'Driver@12345',
    },
    driver: {
      fullName: 'মোহাম্মদ নজরুল ইসলাম',
      phone: '01744-034034',
      email: 'driver34@gari-lagbe.com',
      profileImage: DEMO_PROFILE_IMAGES[3],
      dateOfBirth: new Date('1985-06-16'),
      address: { street: '৭৫ কক্সবাজার সদর', city: 'কক্সবাজার', district: 'কক্সবাজার', postalCode: '4700' },
      licenseNumber: 'DL-COX-2010-034034',
      licenseExpiryDate: new Date('2027-06-30'),
      experienceYears: 13,
      status: 'available',
      rating: 4.5,
      totalTrips: 395,
      emergencyContact: { name: 'নজমা বেগম', phone: '01947-034034', relationship: 'স্ত্রী' },
    },
  },
  {
    user: {
      name: 'মোঃ বাবুল আক্তার',
      email: 'driver35@gari-lagbe.com',
      phone: '01745-035035',
      password: 'Driver@12345',
    },
    driver: {
      fullName: 'মোঃ বাবুল আক্তার',
      phone: '01745-035035',
      email: 'driver35@gari-lagbe.com',
      profileImage: DEMO_PROFILE_IMAGES[4],
      dateOfBirth: new Date('1996-10-31'),
      address: { street: '২৫ গাইবান্ধা সদর', city: 'গাইবান্ধা', district: 'গাইবান্ধা', postalCode: '5700' },
      licenseNumber: 'DL-GAI-2020-035035',
      licenseExpiryDate: new Date('2030-10-31'),
      experienceYears: 3,
      status: 'available',
      rating: 4.0,
      totalTrips: 78,
      emergencyContact: { name: 'বাবুল মিয়া', phone: '01948-035035', relationship: 'বাবা' },
    },
  },
];

const seedDrivers = async () => {
  let created = 0;
  let skipped = 0;

  for (let i = 0; i < driverData.length; i++) {
    const record = driverData[i];
    const profileImage = DEMO_PROFILE_IMAGES[i];

    // Duplicate prevention: check by unique email
    const existingUser = await User.findOne({ email: record.user.email });
    if (existingUser) {
      existingUser.profileImage = profileImage;
      await existingUser.save();
      await Driver.findOneAndUpdate(
        { user: existingUser._id },
        { profileImage: profileImage }
      );
      skipped++;
      continue;
    }

    // Hash password using bcryptjs (12 salt rounds)
    const hashedPassword = await bcrypt.hash(record.user.password, 12);

    // Create the User record
    const newUser = await User.create({
      name: record.user.name,
      email: record.user.email,
      phone: record.user.phone,
      password: hashedPassword,
      role: 'driver',
      profileImage: profileImage,
      isActive: true,
    });

    // Create the Driver record referencing the new User
    await Driver.create({
      user: newUser._id,
      fullName: record.driver.fullName,
      phone: record.driver.phone,
      email: record.driver.email,
      profileImage: profileImage,
      dateOfBirth: record.driver.dateOfBirth,
      address: record.driver.address,
      licenseNumber: record.driver.licenseNumber,
      licenseExpiryDate: record.driver.licenseExpiryDate,
      experienceYears: record.driver.experienceYears,
      status: record.driver.status,
      rating: record.driver.rating,
      totalTrips: record.driver.totalTrips,
      emergencyContact: record.driver.emergencyContact,
      assignedCar: null,
    });

    created++;
  }

  console.log(`Drivers seeded: ${created} created, ${skipped} skipped (already existed).`);
};

module.exports = seedDrivers;

